import Head from 'next/head'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React, {useEffect, useRef, useState} from "react";
import {Scatter} from "react-chartjs-2";
import {Chart, Legend, LinearScale, LineElement, PointElement, Tooltip} from "chart.js";
import Slider from 'rc-slider';
import 'rc-slider/assets/index.css';
import axios from "axios";


const inter = Inter({subsets: ['latin']})

Chart.register(LinearScale, PointElement, LineElement, Tooltip, Legend);

export const options = {
    scales: {
        y: {
            beginAtZero: true,
        },
    },
};

export const data = {
    datasets: [
        {
            label: 'selection',
            data: [],
            backgroundColor: 'rgba(255, 99, 132, 1)',
        },
        {
            label: 'insertion',
            data: [],
            backgroundColor: 'rgb(132,189,255)',
        },
    ],
};


export default function Home() {
    const [index, setIndex] = useState(0);
    const chartRef = useRef(null)
    useEffect(() => {
        console.log("index changed")
        axios.get(`http://127.0.0.1:8080/insertion/${index}`).then(res => {
            console.log(res);
            chartRef.current.data.datasets[1].data = res.data.map((el: number, e: number) => {
                return {
                    x: e,
                    y: el
                }
            });
            console.log(data)
            if (chartRef.current) {
                console.log("test")
                chartRef.current.update()

            }
        })
    }, [index])
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <Scatter ref={chartRef} options={options} data={data}/>
                <Slider max={1000} onChange={(e) => {
                    if (typeof (e) == "number") {
                        setIndex(e)
                    }
                }}/>
            </main>
        </>
    )
}
