import Head from 'next/head'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React, {useEffect, useState} from "react";
import {Scatter} from "react-chartjs-2";
import {Chart, Legend, LinearScale, LineElement, PointElement, Tooltip} from "chart.js";
import Slider from 'rc-slider';
import 'rc-slider/assets/index.css';
import axios from "axios";


const inter = Inter({subsets: ['latin']})

Chart.register(LinearScale, PointElement, LineElement, Tooltip, Legend);

export const options = {
    scales: {
        y: {
            beginAtZero: true,
        },
    },
};

export const data = {
    datasets: [
        {
            label: 'selection',
            data: Array.from({length: 100}, (el, e) => ({
                x: e,
                y: Math.random()
            })),
            backgroundColor: 'rgba(255, 99, 132, 1)',
        },
        {
            label: 'insertion',
            data: Array.from({length: 100}, (el, e) => ({
                x: e,
                y: Math.random()
            })),
            backgroundColor: 'rgb(132,189,255)',
        },
    ],
};


export default function Home() {
    const [index, setIndex] = useState(0);
    useEffect(() => {
        console.log("index changed")
        axios.get(`http://127.0.0.1:8080/test/${index}`).then(res => {
            console.log(res);
        })

    }, [index])
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <Scatter options={options} data={data}/>
                <Slider onChange={(e) => {
                    if (typeof (e) == "number") {
                        setIndex(e)
                    }
                }}/>
            </main>
        </>
    )
}
